// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dkqzzypemdewomxrjftv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRrcXp6eXBlbWRld29teHJqZnR2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIxNDY2NTUsImV4cCI6MjA2NzcyMjY1NX0.2kI1aNqzqcUOYtcQPy_tVzIhzRv6hsDCP10E-KYu8iY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});